FROM golang:1.6

EXPOSE 80

WORKDIR /app

#RUN go get github.com/go-redis/redis && go get github.com/joho/godotenv
#RUN go build -o Controller/controller Controller/controller.go

CMD ["Controller/controller"]
