version: '3.3'

services:
    mysql:
        container_name: ${PROJECT_NAME}_db
        image: mysql:8.0
        ports:
            - "3306:3306"
#        volumes:
#            - ./.data/db:/var/lib/mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        container_name: ${PROJECT_NAME}_php
        build:
            context: ./php
#        ports:
#            - "9000:9000"
#        command: php-fpm -d zend_extension=xdebug.so
        links:
          - mysql
        working_dir: /app
        volumes:
            - "../.:/app"
#            - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
#        environment:
#            PHP_IDE_CONFIG: serverName=${PROJECT_NAME}
#            XDEBUG_CONFIG: remote_port=9001 remote_connect_back=0

    nginx:
        container_name: ${PROJECT_NAME}_nginx
        build:
            context: ./nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php
        volumes:
            - "../.:/app"

    redis:
        container_name: ${PROJECT_NAME}_redis
        entrypoint: redis-server --appendonly yes
        image: redis:4.0.5-alpine
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        ports:
            - "6379:6379"
        volumes:
            - "./.data/redis:/data"
