version: '3.7'

volumes:
    app_volume:
        name: ${PROJECT_NAME}_app_volume
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":${PWD}"

services:
    db:
        container_name: ${PROJECT_NAME}_db
        image: mysql:8.0
        ports:
            - 3306:3306
        volumes:
            - ./.data/db:/var/lib/mysql
        user: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        container_name: ${PROJECT_NAME}_php
        build:
            context: php
#        ports:
#            - 9000:9000
#        command: php-fpm -d zend_extension=xdebug.so
        working_dir: /app
        volumes:
            - app_volume:/app
            - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
        environment:
            PHP_IDE_CONFIG: serverName=${PROJECT_NAME}
            XDEBUG_CONFIG: remote_port=9001 remote_connect_back=0

    nginx:
        build: nginx
        ports:
            - 80:80
            - 443:443
        depends_on:
            - php
        volumes:
            - app_volume:/app

    redis:
        container_name: ${PROJECT_NAME}_redis
        image: redis
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}