index:
    path: /
    controller: App\Controller\DefaultController::index

confirmation:
    path: /confirmation
    controller: App\Controller\DefaultController::confirmation

messagebox:
    path: /messagebox
    controller: App\Controller\DefaultController::messagebox